services:
  frontend:
    image: ghcr.io/k5sha/nextjs-frontend-portfolio:latest
    container_name: portfolio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`k5sha.xyz`)"
      - "traefik.http.routers.nextjs.entrypoints=https"
      - "traefik.http.routers.nextjs.tls=true"
      - "traefik.http.routers.nextjs.tls.certresolver=letsEncrypt"
    restart: always
    networks:
      - traefik_default
    environment:
      - NODE_ENV=production

networks:
  traefik_default:
    external: true
