services:
  frontend:
    image: ghcr.io/k5sha/nextjs-frontend-portfolio:latest
    container_name: portfolio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-web.rule=Host(`k5sha.xyz`)"
      - "traefik.http.routers.portfolio-web.entrypoints=https"
      - "traefik.http.routers.portfolio-web.tls=true"
      - "traefik.http.routers.portfolio-web.tls.certresolver=letsEncrypt"

      - "traefik.http.middlewares.portfolio-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.portfolio-redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.portfolio-redirect.rule=Host(`k5sha.xyz`) || Host(`www.k5sha.xyz`)"
      - "traefik.http.routers.portfolio-redirect.entrypoints=http"
      - "traefik.http.routers.portfolio-redirect.middlewares=portfolio-redirect-to-https"
      - "traefik.http.routers.portfolio-redirect.priority=1"

      - "traefik.http.routers.portfolio-www-redirect.rule=Host(`www.k5sha.xyz`)"
      - "traefik.http.routers.portfolio-www-redirect.entrypoints=https"
      - "traefik.http.routers.portfolio-www-redirect.middlewares=redirect-www-to-root"
      - "traefik.http.routers.portfolio-www-redirect.tls=true"
      - "traefik.http.routers.portfolio-www-redirect.priority=10"

      - "traefik.http.middlewares.redirect-www-to-root.redirectregex.regex=^https://www\\.k5sha\\.xyz/(.*)"
      - "traefik.http.middlewares.redirect-www-to-root.redirectregex.replacement=https://k5sha.xyz/$$1"
      - "traefik.http.middlewares.redirect-www-to-root.redirectregex.permanent=true"
    restart: always
    networks:
      - traefik_default
    environment:
      - NODE_ENV=production

networks:
  traefik_default:
    external: true
